### ISSUE TITLE
delete existing folder before upload

### ISSUE THREAD

**Issue by ogezue** [oklimberg/fastlane-plugin-sftp#3]
I would use this tool for enterprise distribution via company website. Is it possible to delete the existing folder before I upload the new folder?

**Comment by oklimberg** [comment]
Hi,

there is currently no such option. Does the plugin abort if you try to upload files which already exist or why do you want to delete the folder prior creating it again?

**Comment by ogezue** [comment]
Hi - I would like to delete an existing folder before the upload. Have not tried it so far.
It would be great to have this as an option for upload.

**Comment by oklimberg** [comment]
it took some time, but the requested feature is now available via 'delete_target_directory' option.
